#!/usr/bin/bash

prettier  --parser babylon --no-semi --write --single-quote */*.js
prettier  --parser babylon --no-semi --write --single-quote */*.jsx
rm -rf build
yarn build
rsync -ra -e "ssh -p 4520" -P build/ red9@wolf.red9.ir:/usr/local/platform/panel --delete
